### ISSUE TITLE
`empty?` is used against non-string arguments

### ISSUE THREAD

**Issue by yegor256** [yegor256/qbash#28]
```
NoMethodError: undefined method `empty?' for an instance of Integer (NoMethodError)

    cmd = cmd.reject { |a| a.nil? || a.empty? }.join(' ') if cmd.is_a?(Array)
                                      ^^^^^^^
/Users/yb/.rvm/gems/ruby-3.3.5/gems/qbash-0.2.0/lib/qbash.rb:60:in `block in qbash'
/Users/yb/.rvm/gems/ruby-3.3.5/gems/qbash-0.2.0/lib/qbash.rb:60:in `reject'
/Users/yb/.rvm/gems/ruby-3.3.5/gems/qbash-0.2.0/lib/qbash.rb:60:in `qbash'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.1`
